### ISSUE TITLE
Slight modification in data representation

### ISSUE THREAD

**Issue by soumyaaymous** [BhallaLab/MouseBehaviour#10]
Instead of representing the summary like this:

![screenshot from 2017-08-17 15 52 27](https://user-images.githubusercontent.com/14876495/29407825-6bad1d4a-8363-11e7-8aac-48d237570bf9.png)

It would be better if we split the raw rastor plots into one graph and the averaged trace (with SD) to another graph. These would have matching X and Y axes. That makes it easier to compare between the averaged trace of paired and probe trials. Like this: 
![screenshot from 2017-08-17 15 56 43](https://user-images.githubusercontent.com/14876495/29407960-f34664a0-8363-11e7-8777-bb502babfc0a.png)

Currently the Y axis is very squeezed.

**Comment by dilawar** [comment]
Squeezing issue can be fixed. 

Is there nay new information in the plot below. I guess two curves have been plot together to show the contrast. Is that what is needed.

**Comment by soumyaaymous** [comment]
"Is there nay new information in the plot below. I guess two curves have been plot together to show the contrast. Is that what is needed."
Yes. Indeed that is what is needed. It will show the contrast better.

"Squeezing issue can be fixed."
That would be very helpful.

**Comment by dilawar** [comment]
![image](https://user-images.githubusercontent.com/895681/29659199-112247ce-88db-11e7-8e58-5373d16b31a5.png)

**Comment by soumyaaymous** [comment]
Wow...looks really good! Thanks a lot !!

Soumya Bhattacharjee
PhD Scholar and Graduate Student
Bhalla Lab
The National Centre for Biological Sciences
UAS, GKVK
Bellary Road
Bangalore 560065
Karnataka

**Comment by dilawar** [comment]
2 std deviation. One std at either side.
