### ISSUE TITLE
Trial length

### ISSUE THREAD

**Issue by soumyaaymous** [BhallaLab/MouseBehaviour#11]
Trial length is currently 22 seconds. It needs to be cut down to ~11 seconds.
Imaging trigger to be on for
5 seconds --- stim period --- 5 seconds 

The following bit is currently correct and needs no change:
Stim period -
 [Sound (350ms)+trace (250 ms) +puff(50ms)] 

OR

 [Light (50ms)+trace (250 ms) +puff(50ms)]

**Comment by dilawar** [comment]
Pre = 5 seconds.
Post = 5 seconds.
