### ISSUE TITLE
Index error in mouse analysis

### ISSUE THREAD

**Issue by hrishi16** [BhallaLab/MouseBehaviour#12]
![screenshot from 2017-09-22 02-50-05](https://user-images.githubusercontent.com/32175081/30719565-821c1646-9f13-11e7-9f2f-121d5c25e6c0.png)
As seen there is an IndexError: list index out of range
What to do next?

**Comment by dilawar** [comment]
There is a space in directory path which has not been escaped properly.  Either remove the space or use

`$ python analyze_trial.py ~/Upi\ Lab/616_S_1`

Never a good idea to keep spaces in directory names.
