### ISSUE TITLE
_tkinter.TclError in mouse analysis

### ISSUE THREAD

**Issue by hrishi16** [BhallaLab/MouseBehaviour#13]
![screenshot from 2017-09-22 03-24-55](https://user-images.githubusercontent.com/32175081/30720563-8bc96bcc-9f17-11e7-92d5-49f7b7bf35c7.png)

I tried looking up the problem;
2 options were
1)to add '' matplotlib.use('Agg')" right after import and before use
2)to change "backend :agg" in matplotlibrc file

Help needed!

**Comment by dilawar** [comment]
Did you use `-X` or -`Y` switch before ssh.

`$ ssh -X hrishikesh@172.16.y.z`

without `-X` or `-Y`, graphics won't work.  Reopen the issue if this does not fix the issue.
