### ISSUE TITLE
FEC curve

### ISSUE THREAD

**Issue by soumyaaymous** [BhallaLab/MouseBehaviour#15]
In accordance with the field, it would be helpful if we made a Fraction of Eye Closure curve.

Calculated from the trial averaged data.
Base line of the curve is mean of 200ms of eyeblink, before CS. This would be zero.
Highest response (typically occurs during the air puff) is considered one.
-Probe trials also follow the same normalization as the CS+ trials. (i.e. probe trials are not normalised amongst themselves).
-Both probe trials and CS+ curves are shown in single graph.
SD is shown as shaded area around the mean.
Standard X axis ticks. starts at -200, one tick after every 50ms.
-This is in addition to the graphs that we are currently generating.

**Comment by dilawar** [comment]
Closed by latest commit  71f1c15..517df46
