### ISSUE TITLE
New session type required

### ISSUE THREAD

**Issue by soumyaaymous** [BhallaLab/MouseBehaviour#17]
Current session types are S,L and M denoting sound, light and mixed.
Extinction session types are needed.
ME- mixed extinction (mixed session with no US on any trial)
MEL- mixed extinction only light (no US on light trials, usual CS and probe on sound trials)
MES- mixed extinction only sound (no US on sound trials, usual CS and probe on light trials)

To be implemented after discussion in lab meet

**Comment by soumyaaymous** [comment]
From today's discussion, it seems we will go ahead with including these session types
Suggested order: 
MEL
MES
ME

**Comment by dilawar** [comment]
Durations are missing. What are US and CS? Puff/Light/Tone?
I don't maintain CS/US in code. Only stimulus.

**Comment by soumyaaymous** [comment]
Durations: 
CS 50ms
Trace 250 ms
US 50ms

For mixed trials (M or MES or MEL):
Trial 1-5: CS sound
Trial 6-10: CS light
and so on (fifth trial of each block is a probe ie only CS no US)
US is always air puff.


For MEL, No light trial to have US
For MES, no sound trial to have US

**Comment by dilawar** [comment]
If any new protocol is needed, edit the protocol sheet and send the PR.
