### ISSUE TITLE
Need help in opening abf files for analysis purposes in python using pyabf

### ISSUE THREAD

**Issue by anzalks** [BhallaLab/MouseBehaviour#26]
Could you please help me with abf file format, for opening it in python as a table/csv?

**Comment by dilawar** [comment]
The script is `./analysis/abf2other.py`. To use it, pass `-h` option and it will the help messges e.g.


```
usage: abf2other.py [-h] --input INPUT [--output OUTPUT] [--sweep SWEEP]

ABF format to other formats.

optional arguments:
  -h, --help            show this help message and exit
  --input INPUT, -i INPUT
                        Input file
  --output OUTPUT, -o OUTPUT
                        Output file
  --sweep SWEEP, -s SWEEP
                        User defined sweep. Try to guess it.

```

It requires `python3.6` or newer. Install `pyabf` before using it:

    python3 -m pip install pyabf --user 

# Usage

    ./abf2other.py -i /path/to/abffile.abf -o data.csv

Will generate a csv file `data.csv` with all the data in it. This is the general pipeline.
