### ISSUE TITLE
stimulus delivery doesnt match protocol

### ISSUE THREAD

**Issue by soumyaaymous** [BhallaLab/MouseBehaviour#28]
1) light is being used as CS for proto code ''So1''. It should be sound. Same for protocode ''All2''.
2)Wrong 'trial-phase' is being displayed in the 'Animal window'. Displays 'PRE' for a long time. My worry is, it might be writing the wrong trial phase in the data file as well.

**Comment by dilawar** [comment]
You are right. Protocols are broken. Please meet me sometime after lunch to fix this. I am confused about `mixed` protocols on how to implement them. I've not pushed the changes yet.

**Comment by soumyaaymous** [comment]
Behaviour setup powered. Camera attached

**Comment by dilawar** [comment]
See #30 which suppose to fix all these issues.
