### ISSUE TITLE
Analysis code- Summary plots - FEC Calculation and treadmill data

### ISSUE THREAD

**Issue by soumyaaymous** [BhallaLab/MouseBehaviour#32]
FEC has to be calculated for each trial and normalised between 0 (baseline) and 1(max FEC for that trial).
Colours of probe and CS+ traces in FEC graph need to be consistent from day to day. Currently they seem to change.

session summary of tread mill data need to be plotted.

**Comment by dilawar** [comment]
This has been superceded by #33
