### ISSUE TITLE
gaming mouse detector

### ISSUE THREAD

**Issue by Bhumikasingh0110** [BhallaLab/MouseBehaviour#5]
I have placed the sensor near the wheel. Could you please check whether its working or not. If you tell me the commands then I will check it

- [ ] integrate mouse reader into pipeline.

**Comment by dilawar** [comment]
Instruction are kept in `MouseReader/README.md` file.

**Comment by dilawar** [comment]
https://github.com/dilawar/MouseBehaviour/tree/master/MouseReader

**Comment by dilawar** [comment]
- [ ] integrate mouse script into pipeline.
