### ISSUE TITLE
Requesting 2 more seconds for video feed every trial

### ISSUE THREAD

**Issue by ananthamurthy** [BhallaLab/MouseBehaviour#51]
For all sessions, could we record for 2 additional seconds before terminating any trial's video recording
We want to be able to see how the eye-blinks end

**Comment by dilawar** [comment]
@ananthamurthy I am going to merge branch `Hrishi` into `master` branch tonight. I've created branch `BeforeShock` which is today's master branch after fixing #51. Please switch to this branch to use today's code.
