### ISSUE TITLE
Review of PCB designs

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/MouseBehaviour#52]
@hrishi16 @ananthamurthy @soumyaaymous @upibhalla 

Have a look at this PCB design: ~https://labnotes.ncbs.res.in/bhalla/mousebehaviour-cad-files-release-20190707pre2~  https://github.com/BhallaLab/MouseBehaviour/releases/tag/v20190707.rc1

Eyeball the schematic at link above. Let me know if you notice something odd/missing. Tomorrow evening, @mrdorababu is going to drill couple of PCBs.

__IMP__ Required components are here: https://github.com/BhallaLab/MouseBehaviour/releases/download/v20190707.pre2/BOM_MouseBehaviour.xls . This sheet contains component required to make 1 PCB. 

Please place the order as soon as possible for as many PCB as required. My BOM on [mouser.in] is here: https://www.mouser.in/ProjectManager/ProjectDetail.aspx?AccessID=68514497ae .
 If you have mouser accounts, I can share the project with you guys. 

Both GPIO are optional. They support CAMERA TTL pulse for blackfly. They usually have GPIO 6pins port. We can also use 2-pin connectors as well.

- J5 and J6 are complementary to GPIO females J10 and J11.
- J4 and J12 are complementary.

**Comment by dilawar** [comment]
Notes from @mrdorababu

1. The diode which is connected in the solenoid driver need to be in reverse bias. So we need to connect -ve to the 12V.
2. The AGND and DGND are shorted in the PCB. We need to isolate DGND and AGND.

**Comment by dilawar** [comment]
@soumyaaymous @ananthamurthy @hrishi16 reminder. I'd be nice to have one review before it goes to Fab today.

**Comment by hrishi16** [comment]
To whatever extent I know, this should be fine.

**Comment by ananthamurthy** [comment]
Seems ok.. let's proceed

**Comment by dilawar** [comment]
This will go for fab.

**Comment by dilawar** [comment]
![IMG_20190708_183924](https://user-images.githubusercontent.com/895681/60815485-60669980-a1b5-11e9-8ca0-4690a05c13eb.jpg)

Got one made today. I will soldier/mount the components tomorrow morning in workshop. The components needs to be ordered. I've not heard from anyone about order yet. Assuming someone is on it.

**Comment by dilawar** [comment]
Release v2019.07.09.rc1 has thicker tracks.
