### ISSUE TITLE
Modifying protocols

### ISSUE THREAD

**Issue by hrishi16** [BhallaLab/MouseBehaviour#57]
Just adding a line or changing it in the local '.csv' file in 'Protocols' foldr does not start the new protocol. This is the error that comes:

![protocol_error](https://user-images.githubusercontent.com/32175081/62482397-a887d480-b7d2-11e9-90ee-2956377a30c4.png)

**Comment by dilawar** [comment]
Can you copy paste everything in terminal and upload as a text file. The error occured somewhere way up during cmakr phase.

**Comment by dilawar** [comment]
https://unix.stackexchange.com/q/200637/5362

**Comment by hrishi16** [comment]
This doesn't work with the docker terminal. The screenshot above is from the docker gui, couldn't find a way to write it. I also tried executing command in docker using this https://www.edureka.co/community/10588/how-can-i-run-a-docker-exec-command-inside-a-docker-container   .... this didn't exactly run in the docker but the main terminal.

**Comment by dilawar** [comment]
Docker fetches code from github; so unless things are committed to master branch, your local changes won't have any effect inside docker. I'll add changes to make sure that local changes are visible inside docker.

**Comment by hrishi16** [comment]
[100%] Built target cam_server
+ cd ..
+ python3 gui.py --build-dir /root/MouseBehaviour/_docker_build
Traceback (most recent call last):
  File "gui.py", line 25, in <module>
    from screeninfo import get_monitors
  File "/usr/local/lib/python3.6/dist-packages/screeninfo/__init__.py", line 1, in <module>
    from .common import Enumerator, Monitor
  File "/usr/local/lib/python3.6/dist-packages/screeninfo/common.py", line 3, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
Makefile:14: recipe for target 'run' failed
make: *** [run] Error 1


New error after yesterdays  update

**Comment by dilawar** [comment]
screeninfo latest version was released on July 28 which is not compatible with 3.6. it requires dataclass. I'll pin the version to previous release to fix it.

On 7 August 2019 10:50:53 PM IST, hrishi16 <notifications@github.com> wrote:
>[100%] Built target cam_server
>+ cd ..
>+ python3 gui.py --build-dir /root/MouseBehaviour/_docker_build
>Traceback (most recent call last):
>  File "gui.py", line 25, in <module>
>    from screeninfo import get_monitors
>File "/usr/local/lib/python3.6/dist-packages/screeninfo/__init__.py",
>line 1, in <module>
>    from .common import Enumerator, Monitor
>File "/usr/local/lib/python3.6/dist-packages/screeninfo/common.py",
>line 3, in <module>
>    from dataclasses import dataclass
>ModuleNotFoundError: No module named 'dataclasses'
>Makefile:14: recipe for target 'run' failed
>make: *** [run] Error 1
>
>
>New error after yesterdays  update
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/BhallaLab/MouseBehaviour/issues/57#issuecomment-519191354

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
