### ISSUE TITLE
Session files written using docker need permission for edits

### ISSUE THREAD

**Issue by hrishi16** [BhallaLab/MouseBehaviour#58]
The folders conatining data are read ony and cannot be edited. The permission needs to be changed at the docker level I think.

**Comment by dilawar** [comment]
you can change ownership of these files using `chown`

$ sudo chown -c -R hrishikesh:root ~/DATA 

See the manual page of chown for more details. In terminal, type `man chown`.

**Comment by dilawar** [comment]
Here is a good tutorial: https://www.tldp.org/LDP/GNU-Linux-Tools-Summary/html/x9543.htm

**Comment by hrishi16** [comment]
This works. Thanks.
