### ISSUE TITLE
Setting tone frequency?

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/MouseBehaviour#67]
@hrishi16 Change the value at the following line
https://github.com/BhallaLab/MouseBehaviour/blob/801af892f9156c6538076c6a02259157ff213e9d/Arduino/config.h.in#L34

And **not in this line**. 
https://github.com/BhallaLab/MouseBehaviour/blob/801af892f9156c6538076c6a02259157ff213e9d/Arduino/config.h#L34

Note that `config.h` file is created by `config.h.in` file during configuration step. Any change you make in `config.h` will be overwritten.

**Comment by hrishi16** [comment]
This worked. Thanks!
