### ISSUE TITLE
Need session type info

### ISSUE THREAD

**Issue by soumyaaymous** [BhallaLab/MouseBehaviour#8]
HOWTO file doesn't mention the different commands for initiating different types of trials (ie sound, light or mixed)

**Comment by dilawar** [comment]
28a103b  fixes this.

**Comment by dilawar** [comment]
Open it again if it does not fix it.

**Comment by soumyaaymous** [comment]
Hey,
Good news, initial tests seems to have gone very well. Will do full run
with live mouse today. Will let you know how it goes.

Many thanks !

Soumya Bhattacharjee
PhD Scholar and Graduate Student
Bhalla Lab
The National Centre for Biological Sciences
UAS, GKVK
Bellary Road
Bangalore 560065
Karnataka
